# Generated by Django 3.1.4 on 2020-12-14 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_associationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=225, verbose_name='payment description')),
                ('amount', models.FloatField(verbose_name='amount must be payed')),
                ('membership_time', models.DurationField(blank=True, null=True, verbose_name='membership time when a user pay this amount')),
                ('show_in_form', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.costs', verbose_name='cost payed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who payed ths cost')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='form title')),
                ('description', models.TextField(max_length=250, verbose_name='form description')),
                ('email', models.EmailField(max_length=254, verbose_name='form email')),
                ('start_date', models.DateField(verbose_name='day when form is gonna be available')),
                ('days', models.IntegerField(verbose_name='how many days this form is gonna be available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.association', verbose_name='association')),
            ],
        ),
        migrations.AddField(
            model_name='costs',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.form', verbose_name='cost form'),
        ),
    ]
