# Generated by Django 3.1.4 on 2020-12-14 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=125, verbose_name='field label')),
                ('description', models.TextField(max_length=500, verbose_name='field description')),
                ('placeholder', models.CharField(max_length=125, verbose_name='field placeholder')),
                ('show_in_form', models.BooleanField(default=True, verbose_name='show field in form')),
                ('required', models.BooleanField(default=True, verbose_name='field required')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.form', verbose_name='field form')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='field name')),
            ],
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='field data')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.field', verbose_name='field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.fieldtype', verbose_name='field type'),
        ),
    ]
