# Generated by Django 3.1.4 on 2020-12-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201214_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.form', verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.field', verbose_name='field'),
        ),
        migrations.CreateModel(
            name='FormFilledByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.form', verbose_name='field form')),
            ],
        ),
    ]
