# Generated by Django 3.1.4 on 2020-12-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20201214_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfilledbyuser',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formfilledbyuser',
            name='user',
        ),
        migrations.AddField(
            model_name='formfilledbyuser',
            name='user_payed_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.userpayedcosts', verbose_name='user payed cost'),
        ),
    ]
