# Generated by Django 3.1.4 on 2020-12-26 20:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20201217_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='link',
            field=models.URLField(null=True, verbose_name='website link'),
        ),
        migrations.AddField(
            model_name='form',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='form',
            name='photo',
            field=models.ImageField(null=True, upload_to='associations/forms', verbose_name='form image'),
        ),
    ]
