# Generated by Django 3.1.4 on 2020-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20201227_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
