# Generated by Django 3.1.4 on 2020-12-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20201229_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='membership_time',
        ),
    ]
