# Generated by Django 3.1.4 on 2020-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20201229_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='membership_time',
            field=models.IntegerField(null=True, verbose_name='membership time when a user pay this amount'),
        ),
    ]
