# Generated by Django 3.1.4 on 2020-12-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_remove_costs_membership_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='membership_time',
            field=models.IntegerField(null=True, verbose_name='membership time when a user pay this amount'),
        ),
    ]
