# Generated by Django 3.1.4 on 2021-01-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_costs_membership_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='website link'),
        ),
    ]
