# Generated by Django 3.1.4 on 2021-01-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20210103_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='add_to_request',
            field=models.BooleanField(default=False, verbose_name='Add user to join request'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_payed_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.userpayedcosts', verbose_name='user payed cost')),
            ],
        ),
    ]
