# Generated by Django 3.1.4 on 2021-01-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210104_1224'),
        ('membership', '0013_joinrequest_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGroupJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False, verbose_name='accept this join request')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.associationgroup', verbose_name='group')),
                ('user_payed_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.userpayedcosts', verbose_name='user payed cost')),
            ],
        ),
    ]
