# Generated by Django 3.1.4 on 2021-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_associationgroupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.SlugField(max_length=125, null=True, verbose_name='field name'),
        ),
    ]
