# Generated by Django 3.1.4 on 2021-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='title',
            field=models.TextField(max_length=50, null=True, verbose_name='payment description'),
        ),
    ]
