# Generated by Django 3.1.4 on 2021-01-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_costs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfilledbyuser',
            name='user_payed_cost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.userpayedcosts', verbose_name='user payed cost'),
        ),
    ]
