# Generated by Django 3.1.4 on 2021-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_auto_20210131_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='html_name',
            field=models.SlugField(max_length=225, null=True, verbose_name='html field name'),
        ),
    ]
