# Generated by Django 3.1.4 on 2021-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_fieldtype_html_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='form image url'),
        ),
    ]
