# Generated by Django 3.1.4 on 2021-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_auto_20210208_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='html_name',
            field=models.SlugField(blank=True, choices=[('short-text', 'text'), ('long-text', 'textarea'), ('number', 'number'), ('image', 'image'), ('file', 'file'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('select', 'select')], max_length=225, null=True, verbose_name='html field name'),
        ),
    ]
