# Generated by Django 3.1.4 on 2020-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='description',
            field=models.TextField(null=True, verbose_name='a short description'),
        ),
    ]
