# Generated by Django 3.1.4 on 2020-12-08 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
