# Generated by Django 3.1.4 on 2020-12-08 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_baseuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='name of the association')),
                ('description', models.TextField(max_length=1500, verbose_name='description of the association')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='name of the group')),
                ('group_type', models.CharField(choices=[('S', 'STATIQUE'), ('D', 'DYNAMIQUE')], default='S', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.association', verbose_name='association')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='name of the association')),
                ('description', models.TextField(max_length=750, verbose_name='description of the association')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedAssociationMembersNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number', models.IntegerField(verbose_name='expected max number of association members number')),
                ('min_number', models.IntegerField(verbose_name='expected min number of association members number')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='is an association owner')),
                ('is_archived', models.BooleanField(default=False, verbose_name='this user is not a member any more')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.association', verbose_name='association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='member')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.associationgroup', verbose_name='association group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='member')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='association_min_max_numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.expectedassociationmembersnumber', verbose_name='expected max and min number of association members number'),
        ),
        migrations.AddField(
            model_name='association',
            name='association_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.associationtype', verbose_name='the association type'),
        ),
    ]
