# Generated by Django 3.1.4 on 2020-12-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_associationmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='association_min_max_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.expectedassociationmembersnumber', verbose_name='expected max and min number of association members number'),
        ),
    ]
