# Generated by Django 3.1.4 on 2020-12-24 13:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201224_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email adress'),
        ),
        migrations.AddField(
            model_name='association',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
    ]
