# Generated by Django 3.1.4 on 2020-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201224_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
