# Generated by Django 3.1.4 on 2020-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_association_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmembership',
            name='membership_time',
            field=models.IntegerField(verbose_name='membership time '),
        ),
    ]
