# Generated by Django 3.1.4 on 2020-12-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_associationmembership_membership_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmembership',
            name='membership_time',
            field=models.IntegerField(null=True, verbose_name='membership time '),
        ),
    ]
