# Generated by Django 3.1.4 on 2021-01-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210103_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': (('update_association_info', 'Update association Info'), ('view_association_dashboard', 'View association dashboard'), ('add_association_member', 'Add an new association member'), ('delete_association_member', 'Delete association member'), ('view_association_member', 'View association member'), ('manage_group', 'Manage group'), ('manage_association_permissions', 'Manage association permissions'), ('manage_association_form', 'Manage form'))},
        ),
        migrations.AlterModelOptions(
            name='associationgroup',
            options={'permissions': (('add_group_member', 'Add an new group member'), ('delete_group_member', 'Delete group member'), ('view_group_member_info', 'View group member info'), ('update_group_info', 'Update group Info'), ('view_group_dashboard', 'View group dashboard'), ('delete_group', 'Delete group'), ('manage_group_permissions', 'Manage group permissions'))},
        ),
    ]
