# Generated by Django 3.1.4 on 2021-01-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210104_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': (('update_association_info', 'Update association Info'), ('view_association_dashboard', 'View association dashboard'), ('add_association_member', 'Add an new association member'), ('delete_association_member', 'Delete association member'), ('view_association_member', 'View association member'), ('manage_group', 'Manage group'), ('manage_association_permissions', 'Manage association permissions'), ('manage_association_form', 'Manage form'), ('manage_association_payment', 'Manage association payment'))},
        ),
    ]
