# Generated by Django 3.1.4 on 2021-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210106_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='block',
            field=models.BooleanField(default=False, verbose_name='block this association'),
        ),
    ]
